server:
  port: 8084
  servlet:
    context-path: /orders
spring:
  application:
    name: order-service
  datasource:
    url: "jdbc:mysql://localhost:3306/event_ticket_flatform"
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: root
    password: root
  kafka:
    bootstrap-servers: localhost:9094
    consumer:
      group-id: "booking"
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
app:
  services:
    event: http://localhost:8082/events