server:
  port: 8888
app:
  api-prefix: /api/v1
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: identity_service
              uri: http://localhost:8080
              predicates:
                - Path=${app.api-prefix}/identity/**
              filters:
                - StripPrefix=2
            - id: chat_service
              uri: http://localhost:8085
              predicates:
                - Path=${app.api-prefix}/chat/**
              filters:
                - StripPrefix=2
            - id: event_service
              uri: http://localhost:8082
              predicates:
                - Path=${app.api-prefix}/events/**
              filters:
                - StripPrefix=2
            - id: booking_service
              uri: http://localhost:8083
              predicates:
                - Path=${app.api-prefix}/booking/**
              filters:
                - StripPrefix=2
            - id: order_service
              uri: http://localhost:8084
              predicates:
                - Path=${app.api-prefix}/orders/**
              filters:
                - StripPrefix=2
logging:
  level:
    reactor.netty.http.client.HttpClient: DEBUG
    reactor.netty: DEBUG